server:
  port: 8765

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: purchasing-service
          uri: lb://PURCHASING-SERVICE
          predicates:
            - Path=/purchase/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
              - Path=/user/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/